### ISSUE TITLE
新的二维码形式

### ISSUE THREAD

**Issue by gpx0214** [Arnie97/emu-log#1]
新的二维码形式

原文
https://mp.weixin.qq.com/s?__biz=MzA3NzAyMzMyMA==&mid=2247486277&idx=1&sn=bd71f1e14bd3472bf25f46fb4cf8e9ae

样例图片
https://mmbiz.qpic.cn/mmbiz_jpg/TYwR3XRFEvWpwIM3CtlRvpDlibEDgjOCBfjdP5qM83OawLlgsa33LgM95Aezia7KobrC8j1m0OkiabJBOgt4E42AA/640

请求
curl https://mobile.12306.cn/wxxcx/wechat/main/travelServiceDecodeQrcode -d 'c=CR400AF-Z-0216-02-03F&w=h'

**Comment by Arnie97** [comment]
感谢反馈，但是在12306公众号官宣之前，我站已经支持了 XD

由于2022年5月只有昆明局集团大量贴上了这种二维码，当时命名成了 [adapters/kunming.go](https://github.com/Arnie97/emu-log/blob/master/adapters/kunming.go)

后续7月初京局、郑局、武局贴了复兴号，7月底逐渐贴了部分和谐号，但是当时为了避免两个数据源冲突，我没有把京局的数据源切换过来。27号官宣前后，京局完全关掉了自己旧的康之旅系统，我才切过来。截止目前，京、郑、武、呼、昆的大部分车底和沈、广的少数车底接入了铁路畅行码系统。
